version: "3"

services:
  web:
    build: .
    container_name: cian-bot
    command: python3 bot.py
    ports:
      - 80:80
    volumes:
      - ./:/app

networks:
    default:
      name: bridge-nerwork
      external: true