version: "3"

services:
  networks:
    default:
      name: bridge-nerwork
      external: true
  web:
    build: .
    container_name: bot
    command: python3 bot.py
    ports:
      - 80:80
    volumes:
      - ./:/app